name: sample
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  genius_lyrics: ^1.0.1
  http: ^1.1.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - images/saylogo.png


  fonts:
    - family: Musicografi
      fonts:
        - asset: fonts/Musicografi.ttf

    - family: AgainstHistory
      fonts:
        - asset: fonts/Against History.ttf

    - family: TheSignature
      fonts:
        - asset: fonts/Thesignature.ttf

